/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DietTrackerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateAverageBalance"
      | "confidentialProtocolId"
      | "getAllTimestamps"
      | "getLatestRecord"
      | "getRecord"
      | "getRecordCount"
      | "submitDailyData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateAverageBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTimestamps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestRecord",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitDailyData",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateAverageBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDailyData",
    data: BytesLike
  ): Result;
}

export interface DietTracker extends BaseContract {
  connect(runner?: ContractRunner | null): DietTracker;
  waitForDeployment(): Promise<this>;

  interface: DietTrackerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateAverageBalance: TypedContractMethod<
    [numRecords: BigNumberish],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getAllTimestamps: TypedContractMethod<[], [bigint[]], "view">;

  getLatestRecord: TypedContractMethod<
    [],
    [
      [string, string, string, bigint] & {
        caloriesIn: string;
        caloriesOut: string;
        balance: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getRecord: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, string, bigint] & {
        caloriesIn: string;
        caloriesOut: string;
        balance: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getRecordCount: TypedContractMethod<[], [bigint], "view">;

  submitDailyData: TypedContractMethod<
    [
      encCaloriesIn: BytesLike,
      encCaloriesOut: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateAverageBalance"
  ): TypedContractMethod<[numRecords: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllTimestamps"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLatestRecord"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint] & {
        caloriesIn: string;
        caloriesOut: string;
        balance: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, string, bigint] & {
        caloriesIn: string;
        caloriesOut: string;
        balance: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitDailyData"
  ): TypedContractMethod<
    [
      encCaloriesIn: BytesLike,
      encCaloriesOut: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
